### ISSUE TITLE
A1200 config slight config issue

### ISSUE THREAD

**Issue by phaze101** [prb28/vscode-amiga-wks-example#10]
@prb28   The work example for the A1200 on  FS-UAE has a slight error in the Amount of chipmen allocated to the machine in the launch.json file.

Currently this is
"--chip_memory=1024",

but it should be

   "--chip_memory=2048",

The slow mem option I do not understand why it is there. Like that the A1200 is expanded and not standard. 

The A1200 standard has only chip mem of 2K.

FYI and something apart from the above since I do not know how to get in touch with you,  I am trying to organise a stream series of how to write an Amiga game and I will use your extension and this workspace example.  I am tweaking it with my best knowhow since I do not know enough about VC and nor do I have time time. One option that I would like to change in this workspace example is that if say I rename the file gencop.s to say game.s then every thing that was named gencop will be renamed to game. This means also that the startup sequence file will call game and not gencop. I am not logging this as new feature since I do not know if this is even possible.

**Comment by prb28** [comment]
Thanks, I'll change that.

I've started some time ago a new version with an easier way to get a working workspace and have errors.
This kind of feature can be added because it downloads the binaries and the example workspace.
I think it can help a new user.
In you video the setup will be don with on command. 
I would like to have your feedback, and I will try to release it before your first video. If you agree we can discuss the details here : https://github.com/prb28/vscode-amiga-assembly/discussions/167
